server:
  port: 9080
  servlet:
    context-path: /api

spring:
  application:
    name: practice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: root

  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
