server:
  port: 9080
  servlet:
    context-path: /api
spring:
  application:
    name: practice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: root

  # Redis configuration
  redis:
    host: localhost
    port: 6379
    password: #123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

  session:
    timeout: 86400
  # swagger configuration information
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

swagger:
  enable: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %clr(%-5level){green} %clr(${pid}){magenta} --- [%20thread] %clr(%logger{42}){cyan} : %clr(%msg%n){yellow}"
  level:
    root: INFO
  file:
    path: d:/log/history
    name: d:/log/recordLog.log
  logback:
    rollingpolicy:
      file-name-pattern: "${logging.file.path}/%d{yyyy-MM-dd}/sysLog-%d{yyyy-MM-dd-HHmmss}-%i.log"
      max-file-size: 50KB
      max-history: 7
      total-size-cap: 100MB


basic:
  #  这两种（下划线和横杠都可以解析成驼峰形式）
  file_upload_path: D:\tmp\usercenter\tempFile
  file-save-path: D:\tmp\usercenter\saveFile
  file_ipWhite_file: D:\tmp\ipWhite\ipwhitelist.txt
  file-temp-pdf: D:\tmp\usercenter\tempFile\pdf_file\Temp.pdf
  address: hunan
